Slightly Better TimePicker
GeoGuess/GeoGuess pull request #486
Opened 2022-06-27 20:35 UTC by EliteAsian123

## Types of Changes

- [x] Bug fix: Added padding to the seconds so it displays `00` instead of just `0`
- [x] Adjustment: The time updates *while* the slider is being moved instead of after it has moved
- [x] Adjustment: Slider ticks 

## Screenshots (if appropriate):
**Before:**<br>
![Before](https://i.imgur.com/O5ickts.gif)

**After:**<br>
![After](https://i.imgur.com/IUNDzBB.gif)

2022-06-29 08:23 UTC, BilelJegham requested changes
Hello, thanks for you contribution.

I write a small feedback.

Best regards,
Bilel

2022-06-29 14:22 UTC, EliteAsian123 commented on src/components/shared/TimePicker.vue
> +        getSeconds() {
Yes, it should be. Sorry, I'm newer to Vue.

2022-06-30 16:52 UTC, BilelJegham approved these changes
Looks good for me.

Thanks @EliteAsian123 


@all-contributors please add for code

2022-06-30 16:52 UTC, merged

2022-06-30 16:53 UTC, BilelJegham commented
@all-contributors please add @EliteAsian123 for code