Space/enter for "Guess" and "Next Round"
GeoGuess/GeoGuess pull request #490
Opened 2022-07-01 21:39 UTC by EliteAsian123

## Types of Changes

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Description
While in-game, you can now press `space` or `enter` to guess a selected location. You can also use `space` or `enter` to proceed to the next round while in the round summary screen.

2022-07-10 17:05 UTC, BilelJegham reviewed
Hello, thanks for your contribution.

Don't you think it will be great to not only focus on the next button?

It would be great to think "Keyboard accessibility" of all parts of GeoGuess : 
 - Game definition: settings, mode, maps. Add accessibility to the card settings 
 - Guessing, define the location with your keyboard
 
 Best regards

2022-07-10 21:00 UTC, EliteAsian123 commented on src/components/Maps.vue
> +            :disabled="!canGuess()"
Yes, sorry. Again.

2022-07-10 21:04 UTC, EliteAsian123 commented
Yes, if I have time in the future I will look into adding more keyboard accessibility to GeoGuess. Thanks!

2022-08-01 21:35 UTC, EliteAsian123 commented
Hello, congrats on v1.0.0. I've confirmed that this pull request still works on the new version.

2022-08-02 20:05 UTC, BilelJegham commented
Hello @EliteAsian123, 
As said below, this PR is not enough to improve the user experience. We need to think globally by adding "Keyboard accessibility" across the platform.

Not only on one button.
It will be complete if we can :
 1. start a game
 2. play
   a. Select position
   b. Guess
   c. Go to the next round

2022-08-02 20:06 UTC, BilelJegham requested changes
Ok for the code.

But it's only on the submit btn

2022-08-02 23:16 UTC, EliteAsian123 commented
Hi. Unfortunately, I do not have the time to add Global Keyboard Accessibility at the moment so I will be closing the pull request. If I decide to take it on in the future, I will re-open the pull request. Thanks!

2022-08-02 23:16 UTC, closed without merging